apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-monitoring-credentials
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-monitoring-secret-store
    kind: SecretStore
  target:
    name: mariadb-monitoring-secret
    creationPolicy: Owner
  data:
    - secretKey: exporter-password
      remoteRef:
        key: exporter/mariadb
        property: password
