apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-credentials
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: mariadb-secret
    creationPolicy: Owner
  data:
    - secretKey: root-password
      remoteRef:
        key: database/mariadb
        property: root-password
    - secretKey: db-password
      remoteRef:
        key: database/mariadb
        property: db-password
    - secretKey: db-user
      remoteRef:
        key: database/mariadb
        property: db-user
    - secretKey: healthcheck-password
      remoteRef:
        key: database/mariadb
        property: healthcheck-password
