apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-external-secret
  namespace: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: mariadb-secret-eso
    creationPolicy: Owner
  data:
    - secretKey: root-password
      remoteRef:
        key: production/mariadb
        property: root-password
    - secretKey: db-password
      remoteRef:
        key: production/mariadb
        property: db-password
    - secretKey: db-user
      remoteRef:
        key: production/mariadb
        property: db-user
    - secretKey: healthcheck-password
      remoteRef:
        key: production/mariadb
        property: healthcheck-password
