apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dvwa-credentials
  namespace: dvwa
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: dvwa-secret
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: dvwa/credentials
        property: db-password
    - secretKey: db-user
      remoteRef:
        key: dvwa/credentials
        property: db-user
