apiVersion: v1
kind: ServiceAccount
metadata:
  name: dvwa-sva
  namespace: production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb-sva
  namespace: production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: web-app-role
  namespace: production
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: database-role
  namespace: production
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: database-rb
  namespace: production
subjects:
  - kind: ServiceAccount
    name: mariadb-sva
    apiGroup: ""
roleRef:
  kind: Role
  name: database-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-app-rb
  namespace: production
subjects:
  - kind: ServiceAccount
    name: dvwa-sva
    apiGroup: ""
roleRef:
  kind: Role
  name: web-app-role
  apiGroup: rbac.authorization.k8s.io
