apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    kubernetes.io/metadata.name: cert-manager
    name: cert-manager
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.35

