apiVersion: constraints.gatekeeper.sh/v1beta1
kind: BlockLatestImageTag
metadata:
  name: block-latest-image
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet"]
    namespaces:
      - dvwa
      - database
