apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DenyPrivilegedContainer
metadata:
  name: deny-privileged-containers
spec:
  match:
    excludedNamespaces:
      - falco
      - observability
      - kube-system
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet", "DaemonSet"]
      - apiGroups: ["batch"]
        kinds: ["Job"]
