apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EnforceNonRootUser
metadata:
  name: enforce-non-root-user
spec:
  match:
    excludedNamespaces:
      - falco
      - kube-system
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet", "DaemonSet"]
      - apiGroups: ["batch"]
        kinds: ["Job"]

