apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dvwa
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/actualmira/DevSecOps-EKS-CloudNative-Platform.git
    targetRevision: main
    path: k8s/dvwa
  destination:
    server: https://kubernetes.default.svc
    namespace: dvwa
  syncPolicy:
    automated: {}
