apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://falcosecurity.github.io/charts
      chart: falco
      targetRevision: "4.15.0"
      helm:
        valueFiles:
          - $values/k8s/falco/falco-eks-values.yaml
    - repoURL: https://github.com/actualmira/DevSecOps-EKS-CloudNative-Platform.git
      targetRevision: main
      path: k8s/falco
      directory:
        exclude: "*-values.yaml"
    - repoURL: https://github.com/actualmira/DevSecOps-EKS-CloudNative-Platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated: {}
