apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "91.8.1"
      helm:
        valueFiles:
          - $values/k8s/observability/kube-prometheus-values.yaml
    - repoURL: https://github.com/actualmira/DevSecOps-EKS-CloudNative-Platform.git
      targetRevision: main
      path: k8s/observability
      directory:
        exclude: "*-values.yaml"
    - repoURL: https://github.com/actualmira/DevSecOps-EKS-CloudNative-Platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true
