apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: "3.5.0"
    helm:
      values: |
        clusterName: devsecops-dev-cluster
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::853184314323:role/devsecops-dev-aws-lbc-role
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated: {}
