global:
  tlsDisable: true

injector:
  enabled: false

csi:
  enabled: false

ui:
  enabled: false

server:
  serviceAccount:
    create: true
    name: vault

  nodeSelector:
    role: isolated

  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "isolated"
      effect: "NoSchedule"

  authDelegator:
    enabled: true

  volumes:
    - name: tmp
      emptyDir: {}

  volumeMounts:
    - name: tmp
      mountPath: /tmp

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: ebs-sc

  auditStorage:
    enabled: true
    size: 5Gi
    storageClass: ebs-sc
    mountPath: /vault/audit

  ha:
    enabled: false

  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"

  statefulSet:
    securityContext:
      pod:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      container:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL

  livenessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 10

  readinessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 10

  standalone:
    enabled: true
    config: |
      ui = false
      listener "tcp" {
        address = "0.0.0.0:8200"
        tls_disable = true
      }
      storage "file" {
        path = "/vault/data"
      }
      seal "awskms" {
        region     = "eu-west-1"
        kms_key_id = "alias/devsecops-dev-vault-unseal"
      }
